version: '3'

services:
  site:
    image: framething-site
    build:
      context: .
      dockerfile: development.Dockerfile
    ports:
      - 50000:5000
      - 50001:5001
    depends_on:
      - postgres
    environment:
      ASPNETCORE_ENVIRONMENT: 'Development'
    volumes:
      - ./:/app/
  
  postgres:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: topsecret
      POSTGRES_USER: framething
    ports:
      - 50002:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:5
    ports:
      - 50003:6379
    volumes:
      - redis:/data

volumes:
  postgres:
  redis:
