version: '3'

services:
  site:
    image: framething-site
    build:
      context: .
      dockerfile: development.Dockerfile
    ports:
      - "26873:26873"
      - "26874:26874"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT="Development"
      - Google__ClientId
      - Google__ClientSecret

    volumes:
      - ./:/app/
  
  postgres:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: topsecret
      POSTGRES_USER: framething
    ports:
      - "26875:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:5
    ports:
      - "26876:6379"
    volumes:
      - redis:/data

volumes:
  postgres:
  redis:
